### ISSUE TITLE
Grant number

### ISSUE THREAD

**Issue by dnkennedy** [CRNC/crnc.github.io#1]
Hi, can we get the grant number listed on the website mainpage: NIH-NIBIB P41 EB019936 and a link to the reporter page: https://projectreporter.nih.gov/project_info_description.cfm?aid=8999833&icde=29244418&ddparam=&ddvalue=&ddsub=&cr=7&csb=default&cs=ASC

**Comment by satra** [comment]
@dnkennedy - can we use the automatic page generator now so that you can create a basic site quite quickly?

**Comment by satra** [comment]
@dnkennedy - do you want to give it a shot?

goto: https://github.com/CRNC/crnc.github.io/settings

and click on automatic page generator. you will then be able to choose a theme, etc.,. you can get a basic site up very quickly.

**Comment by dnkennedy** [comment]
in looking at the automatic page generator it says:

Overwrite site
Replace your existing site by using our automatic page generator. Author your content in our Markdown editor, select a theme, then publish.

Not that there's is much there to get squashed there now, but I did want to preview before squashing the current...

**Comment by satra** [comment]
@dnkennedy - it's really wysiwig before you publish. so effectively you are previewing while creating.

**Comment by dnkennedy** [comment]
so if this blasts the current index.html, that's OK, github _could_ get me back to the version of yesterday, right? That's what github does.

**Comment by dnkennedy** [comment]
ok, done.

**Comment by satra** [comment]
yes that's exactly what github does (with most things - code, wiki, pages)
